export const LANGUAGES = [
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸", hasScript: false, color: "#ef4444" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷", hasScript: false, color: "#3b82f6" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵", hasScript: true, scriptName: "Hiragana/Katakana", color: "#ec4899" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷", hasScript: true, scriptName: "Hangul", color: "#8b5cf6" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳", hasScript: true, scriptName: "Devanagari", color: "#f97316" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪", hasScript: false, color: "#eab308" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳", hasScript: true, scriptName: "Hanzi", color: "#ef4444" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦", hasScript: true, scriptName: "Arabic Script", color: "#10b981" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇧🇷", hasScript: false, color: "#22c55e" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺", hasScript: true, scriptName: "Cyrillic", color: "#6366f1" },
];

export const HIRAGANA_DATA = [
  { character: "あ", romaji: "a", audioText: "あ" },
  { character: "い", romaji: "i", audioText: "い" },
  { character: "う", romaji: "u", audioText: "う" },
  { character: "え", romaji: "e", audioText: "え" },
  { character: "お", romaji: "o", audioText: "お" },
  { character: "か", romaji: "ka", audioText: "か" },
  { character: "き", romaji: "ki", audioText: "き" },
  { character: "く", romaji: "ku", audioText: "く" },
  { character: "け", romaji: "ke", audioText: "け" },
  { character: "こ", romaji: "ko", audioText: "こ" },
  { character: "さ", romaji: "sa", audioText: "さ" },
  { character: "し", romaji: "shi", audioText: "し" },
  { character: "す", romaji: "su", audioText: "す" },
  { character: "せ", romaji: "se", audioText: "せ" },
  { character: "そ", romaji: "so", audioText: "そ" },
  { character: "た", romaji: "ta", audioText: "た" },
  { character: "ち", romaji: "chi", audioText: "ち" },
  { character: "つ", romaji: "tsu", audioText: "つ" },
  { character: "て", romaji: "te", audioText: "て" },
  { character: "と", romaji: "to", audioText: "と" },
  { character: "な", romaji: "na", audioText: "な" },
  { character: "に", romaji: "ni", audioText: "に" },
  { character: "ぬ", romaji: "nu", audioText: "ぬ" },
  { character: "ね", romaji: "ne", audioText: "ね" },
  { character: "の", romaji: "no", audioText: "の" },
  { character: "は", romaji: "ha", audioText: "は" },
  { character: "ひ", romaji: "hi", audioText: "ひ" },
  { character: "ふ", romaji: "fu", audioText: "ふ" },
  { character: "へ", romaji: "he", audioText: "へ" },
  { character: "ほ", romaji: "ho", audioText: "ほ" },
  { character: "ま", romaji: "ma", audioText: "ま" },
  { character: "み", romaji: "mi", audioText: "み" },
  { character: "む", romaji: "mu", audioText: "む" },
  { character: "め", romaji: "me", audioText: "め" },
  { character: "も", romaji: "mo", audioText: "も" },
  { character: "や", romaji: "ya", audioText: "や" },
  { character: "ゆ", romaji: "yu", audioText: "ゆ" },
  { character: "よ", romaji: "yo", audioText: "よ" },
  { character: "ら", romaji: "ra", audioText: "ら" },
  { character: "り", romaji: "ri", audioText: "り" },
  { character: "る", romaji: "ru", audioText: "る" },
  { character: "れ", romaji: "re", audioText: "れ" },
  { character: "ろ", romaji: "ro", audioText: "ろ" },
  { character: "わ", romaji: "wa", audioText: "わ" },
  { character: "を", romaji: "wo", audioText: "を" },
  { character: "ん", romaji: "n", audioText: "ん" },
];
